### ISSUE TITLE
Should have tests for the DAOs

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#104]
we should have basic tests for all the DAOs

**Comment by robstryker** [comment]
What kind of basic tests, exactly? Would you like to test that the constructors, getters, and setters work properly? Maybe I'm lazy but this seems like overkill to me.

**Comment by adietish** [comment]
I agree that there are tests should first cover the classes that contain proper logic. But then the DAOs also need tests to assert their basic. Remember when there was this issue lately where a DAO couldn't be instantiated and you found out that there were more problems across the board. We would have found out earlier if we had tests for them ;)

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/118
