### ISSUE TITLE
starting a cdk server with invalid (registration-) credentials leaves me stuck

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#117]
steps:
1) EXEC: create a cdk server with erroneous credentials for registration
2) EXEC: start the server

Result:
Server gets back to stopped state, but the minishift binary is still running. Starting a server is not possible any more since the cdk binary will complain that it is already running. So as a user you're stuck. You have to kill the minishift binary via kill comand in the shell.

Output when the server is started:
```
ServerOutput: org.jboss.tools.rsp.api.dao.ServerType@2f7e2c83:cdk [org.jboss.tools.openshift.cdk.server.type.minishift.cdk.3x:cdk:1539963508084:p0][2]  FAIL [4s]

ServerOutput: org.jboss.tools.rsp.api.dao.ServerType@2f7e2c83:cdk [org.jboss.tools.openshift.cdk.server.type.minishift.cdk.3x:cdk:1539963508084:p0][1] Error to register VM: ssh command error:
command : sudo -E subscription-manager register --auto-attach --username adietish --password ********
err     : exit status 1
output  : Registering to: subscription.rhsm.redhat.com:443/subscription
adietish cannot register with any organizations.


Server process terminated: org.jboss.tools.rsp.api.dao.ServerType@2f7e2c83:cdk @ org.jboss.tools.openshift.cdk.server.type.minishift.cdk.3x:cdk:1539963508084:p0
Server state changed: org.jboss.tools.rsp.api.dao.ServerType@2f7e2c83:cdk to stopped
```

ps command that shows that the minishift binary is still runing:
```
26873   ??  S      0:37.85 /usr/local/bin/docker-machine-driver-xhyve xhyve -A -U 21E44EC3-4468-4CDC-8E28-8C02BB89B863 -c 2 -m 4096M -l com1,autopty -s 0:0,hostbridge -s 31,lpc -s 2:0,virtio-net -s 3:0,ahci-cd,/Users/adietish/.minishift/machines/minishift/boot2docker.iso -s 4:0,ahci-hd,/dev/rdisk2 -f kexec,/Users/adietish/.minishift/machines/minishift/vmlinuz0,/Users/adietish/.minishift/machines/minishift/initrd0.img,initrd=initrd0.img root=live:CDLABEL=minishift-rhel-1.0.0-1 rootfstype=auto ro rd.live.image quiet no_timer_check console=ttyS0 console=tty0 net.ifnames=0 biosdevname=0 rhgb rd.luks=0 rd.md=0 rd.dm=0  -F /Users/adietish/.minishift/machines/minishift/minishift.pid
```

**Comment by robstryker** [comment]
The problem here is that a minishift status command reutrns the following:

Minishift:  Running
Profile:    minishift
OpenShift:  Stopped
DiskUsage:  1% of 18G

In JBT we mark this as a failure, because openshift isn't started.  If we all feel that a start of 'minishift' is separate from a start of the 'openshift' sub-service, then I can just check the status of minishift and not any of its sub-services. If we decide that's better...

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/120

**Comment by robstryker** [comment]
Merged
