### ISSUE TITLE
server should indicate what field was erroneous when responding to a "add server" request 

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#124]
to add a server the client collects all required parameters and sends them in a single request over to the server. If one of those parameters is erroneous the server currently rejects the "add server" request without saying what parameter was erroneous. 
If the server was repeating the inputs, the client could reuse the inputs and just re-prompt the user for the erroneous one.

**Comment by robstryker** [comment]
@adietish  care to review / test out https://github.com/redhat-developer/rsp-server/pull/126   ?

**Comment by adietish** [comment]
resolved with #126 being merged. Closing.
