### ISSUE TITLE
Required Attributes should be ordered, not sent in a Map

### ISSUE THREAD

**Issue by robstryker** [redhat-developer/rsp-server#127]
Sending the required attributes in a map leads to a strange behavior for CDK where the password may be requested before a username is requested. This will confuse users, who generally want to be prompted for details in a correct order. 

I believe this will require API changes to do properly.

**Comment by adietish** [comment]
noticed this. +1 on this enhancement.

**Comment by adietish** [comment]
PR was merged. Closing.
