### ISSUE TITLE
Integration tests for RSP

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/rsp-server#14]
Get some integration tests up and possibly hook them to the PR checker so we know the API has been tested out on each change.
I'm inclined to make them quite lightweight, most likely in nodejs/typescript. The question is, where to put them.
@robstryker would you mind having essentially a nodejs project in this repo to serve as integration tests?

**Comment by robstryker** [comment]
Hi Jan:

We should think about the best way to do this. We're trying to switch to a tycho build with test plugins. This is still quite easy to do in java. You can just open a socket to host:port and shove some json down the pipe. 

There are examples of this in the lsp4j test suite. Not sure if that's reasonable or not... thoughts?

**Comment by jrichter1** [comment]
Resolved in #34
