### ISSUE TITLE
Publishing requires file-watching service

### ISSUE THREAD

**Issue by robstryker** [redhat-developer/rsp-server#151]
When a user asks us to publish or add a given deployment to a server, we need to make sure that when that file changes, we update the sync state in the model as one that requires a deployment, ie, a change has occurred. 

This will require use of the java nio file watching. However, since the most likely thing to be published will be built artifacts, perhaps from a maven (or other) build, the odds are high that the folder we'd like to watch will be deleted in the process. Java's nio watcher cannot handle a folder that's removed, and will keep watching it forever. 

To fix this, we need to watch some of the parent folders, to properly respond when our target folder is removed and re-generated, so that we stop watching the old folder and start watching the new by the same path, so that subsequent events are properly received.

**Comment by jeffmaury** [comment]
So it the folder is deleted, then you get your status so the question is: will you get an event in case the watched folder is deleted ?

**Comment by robstryker** [comment]
watched folder being deleted throws no event, unless you're watching the parent folder too ;)

**Comment by robstryker** [comment]
| * 18c637b - Issue 168 - clean mvn build mark deployment as requiring publish (2 weeks ago) <Rob Stryker>
| * c5bcbcc - Use executor service instead of thread in filewatcher service (2 weeks ago) <Rob Stryker>
| * fb84735 - Small cleanup as per PR (2 weeks ago) <Rob Stryker>
| * 6774494 - Automatic recognition of changed deployment plus test case (3 weeks ago) <Rob Stryker>
| * 52d4076 - Fix small unit test failures (3 weeks ago) <Rob Stryker>
| * 7e93ca6 - Allow deployments to register with the file watcher service (3 weeks ago) <Rob Stryker>
| * 6581635 - Issue 151: Add a file-watcher API (3 weeks ago) <Rob Stryker>
