### ISSUE TITLE
Define acceptance criteria for the publishing in rsp-server

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#162]
we discussed that we need to have some acceptance criteria for publishing in rsp-server. The added benefit is that anyone can picture what publishing will be able to do.
(CC. @mohitsuman)
@jeffmaury @robstryker can you please provide these?

**Comment by jeffmaury** [comment]
Here is my first proposition:

- Wildly (from github.com/wildfly/quickstart)
 kitchensink (WAR and exploded WAR)
 kitchensink-ear (EAR and exploded EAR)
 ejb-in-war (WAR and exploded WAR)
 ejb-in-ear (EAR and exploded EAR)

- EAP (from https://github.com/jboss-developer/jboss-eap-quickstarts)
 kitchensink (WAR and exploded WAR)
 kitchensink-ear (EAR and exploded EAR)
 ejb-in-war (WAR and exploded WAR)
 ejb-in-ear (EAR and exploded EAR)

**Comment by odockal** [comment]
@jeffmaury @adietish Guys, could you please provide a bit more information as of what should I do in this issue? Name could suggest that I am supposed to defined what "publishing" in rsp-server actually means - is. but Jeff's comment would aim to actually verify such behavior... (on multiple projects). So... Which one is it? Thanks

**Comment by jeffmaury** [comment]
What I meant is that we should have integration tests that would check the listed projects in the various configurations (exploded or not)

**Comment by odockal** [comment]
@jeffmaury I am working now on the itests that will verify the deployment of that set of projects. Patch should arrive tomorrow.
