### ISSUE TITLE
codecov wont report correct code coverage

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#163]
In PR #159 - which clearly only refactors existing classes and adds lots of tests for them - codecov reports a decrease of code coverage by -0.1%, which can't be true. In Eclipse/Eclemma code coverage went clearly up. There's no sonar report for it given that this is in a PR currently.

**Comment by adietish** [comment]
codecov was configured in the following commit: https://github.com/redhat-developer/rsp-server/commit/5d2d885d16e6a21b231f237b78968cef26e0f349

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/164
