### ISSUE TITLE
Warn users of MacOS & non-sun jdk that WatchService is not reliable

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#199]
As discussed in https://github.com/redhat-developer/rsp-server/issues/168#issuecomment-442505124 the jdk WatchService is not reliable if it's not used with the high sensitivity flag. This flag unfortunately is specific to sun jdks. This will cause unexpected and unreliable behaviour in non-sun jdks on MacOS (as discussed in https://github.com/redhat-developer/rsp-server/issues/168#issuecomment-442726962). 
We should therefore warn MacOS users that watching files is not reliable when using MacOS and a non-sun jdk.

**Comment by adietish** [comment]
this is related to #168

**Comment by robstryker** [comment]
Out of date and also no real way for the UI to know that the java is non-sun and even if it did discover that, there's no obvious place to list that deficiency. Closing as wont-fix
