### ISSUE TITLE
Unit Tests coverage report with EclEmma in standard mode

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/rsp-server#21]
codecov supports EclEmma code coverage for Java. Unit tests should be running in CI using [Standard instrumentation mode](https://www.eclemma.org/research/instrumentingosgi/index.html).

**Comment by dgolovin** [comment]
@jrichter1 do you want to take this one?

**Comment by jrichter1** [comment]
Wouldn't it be easier to just use something like JaCoCo though?
