### ISSUE TITLE
enable running integration tests in jenkins

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#218]
we moved integration tests to the *integration-tests* maven profile. We should now fix make sure those are run in jenkins.

**Comment by odockal** [comment]
@adietish I have added an intengration-tests profile to rsp-server-prcheck-matrix jenknis job build step, and verified that itests were actually run, see test [report]. Now it should be run every time when there is an incoming PR.

[report]: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Adapters/view/RSP/job/rsp-server-prcheck-matrix/297/label=rhel7/testReport/

**Comment by robstryker** [comment]
@odockal  Can you verify this is now working and the issue can be closed? Thanks.

**Comment by odockal** [comment]
@robstryker I can confirm. Running on both platforms, and passing on these as well. Close this one please. Thanks.

**Comment by adietish** [comment]
@odockal thx! Closing.
