### ISSUE TITLE
use sonar for code inspection (replace codecov)

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#234]
We currently use codecov to monitor test coverage. We should move over to sonar since it's far superior and provides far more indicators (test coverage, code smells, etc.).
@bdshadow prepared this (look here: https://sonarcloud.io/dashboard?id=org.jboss.tools.rsp%3Aparent) but didn't have the time to finish it.

**Comment by adietish** [comment]
CC: @jkopriva

**Comment by bdshadow** [comment]
@jkopriva just gave you all admin permissions to rsp-server project in the sonarcloud server.
Ping me, in case of issues. It must be almost just a copy-paste from pom.xml-s of jbosstools projects
