### ISSUE TITLE
Fix sonar settings for PR check job

### ISSUE THREAD

**Issue by jkopriva** [redhat-developer/rsp-server#239]
Follow up of: https://github.com/redhat-developer/rsp-server/issues/234

**Comment by jkopriva** [comment]
PR check job is fixed and decorations are working in PRs.

**Comment by adietish** [comment]
@jkopriva so we can now resolve this, right?

**Comment by jkopriva** [comment]
@adietish yes, this can be closed, Thank you!

**Comment by adietish** [comment]
@jkopriva ok, cool.
