### ISSUE TITLE
Delete codecov once sonar is fully configured

### ISSUE THREAD

**Issue by jkopriva** [redhat-developer/rsp-server#243]
Should be done after https://github.com/redhat-developer/rsp-server/issues/239 is resolved.

**Comment by jkopriva** [comment]
Link to sonar: https://sonarcloud.io/dashboard?id=org.jboss.tools.rsp%3Aparent

**Comment by adietish** [comment]
@jkopriva can we switch to sonar and remove codecov?

**Comment by adietish** [comment]
@jkopriva I see sonar running, are we ready to switch from codecov to sonar?

**Comment by jkopriva** [comment]
@adietish I will review it and remove codecov.
