### ISSUE TITLE
Add option to enable tracing for RSP servrer's json requests and responses

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/rsp-server#25]
Would be good to be able to enable tracing for server to print out json rpc requests/responses for debugging purposes.

**Comment by robstryker** [comment]
I have a PR up to do it.  You have to do -Drsp.log.level=4  when running it. 

https://github.com/redhat-developer/rsp-server/pull/30

**Comment by robstryker** [comment]
Fixed it
