### ISSUE TITLE
Cancel "Download Runtimes" (via esc) results in error "Cannot read property 'id' of undefined"

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#261]
steps: 
1. EXEC: pick "Download Runtimes" in "Servers" context menu
2. ASSERT: list of available runtimes is presented
3 EXEC: hit "esc" to close the input message that lists all runtimes

Result:
![image](https://user-images.githubusercontent.com/25126/53741716-462f4e80-3e97-11e9-8e35-68fcd33b1717.png)

**Comment by robstryker** [comment]
Fixed by https://github.com/redhat-developer/vscode-adapters/pull/262
