### ISSUE TITLE
servers should provide their icon

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#290]
since 3rd party can provide their own servers, rsp-server should allow them to provide their icon to consuming UI.

ideally ServerType would not only provide id, visibileName, description but also the icon:
```
interface ServerType {
        id: string;
        visibleName: string;
        description: string;
    }
```

**Comment by adietish** [comment]
this is related to #292

**Comment by robstryker** [comment]
https://github.com/redhat-developer/vscode-server-connector/issues/292  has been closed. This is clearly a UI issue. The RSP itself provides no icons.
