### ISSUE TITLE
CLI incorrectly supports exploded deployment

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rsp-server#297]
CLI does not correctly support exploded deployment. If you try to add a folder without extension then this fails

**Comment by robstryker** [comment]
It's always nice to include a log when filing a bug, el jefe ;) 

add deployment
Please select a server:
1) wf14a

1
Please enter a filesystem path of your deployment:

/home/rob/tmp/quickstarts/quickstart/kitchensink/target/kitchensink/
Please set an output name for this deployment (blank line for default):

kitchensink.war
Status ERROR: org.jboss.tools.rsp.server.wildfly code=0 Server wf14a cannot add deployable from /home/rob/tmp/quickstarts/quickstart/kitchensink/target/kitchensink/ null


Fixing it now.

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/300
