### ISSUE TITLE
Should not allow to change the path in an existing DeployableReference (#setPath)

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#310]
A user programmer should not be able to change the path in a DeployableReference once it's instantiated. This is especially important since the path is used as a key to store DeployableState(s) in ServerPublishStateModel:

```
	public void setDeployablePublishState(DeployableReference reference, int publishState) {
		DeployableState ds = getDeployableState(reference);
		if (ds == null) {
			return;
		}
		DeployableState next = createDeployableState(reference, publishState, ds.getState());
		String key = getKey(reference);
		getStates().put(key, next);
		if( publishState == ServerManagementAPIConstants.PUBLISH_STATE_NONE) {
			clearDelta(key);
		}
		updateServerPublishStateFromDeployments();
	}
```
```
	@Override
	public DeployableState getDeployableState(DeployableReference reference) {
		DeployableState ds = getStates().get(getKey(reference));
		...
	}
```
The key to store the ```DeployableState```s is based on the path that's stored in the ```DeployableReference```:
```
	protected String getKey(DeployableReference reference) {
		...
		return reference.getPath();
	}
```

**Comment by adietish** [comment]
quoting @robstryker at: https://github.com/redhat-developer/rsp-server/pull/306#discussion_r280124080

There's only 4 possible entities calling setPath. 

1) The client. The client may use setPath for 2 reasons. 
     a) To instantiate it for sending to the server. This is a valid use of setPath
    b) Setting the path on an object they received FROM the server. This is a nonsensical use of the API and has no effect to anything on the server. There is no reason to do this. 
2) lsp4j, either in seriailziing or unserializing. This is a valid (and required) use of the API. 
3) rsp-server itself.  The rsp-server framework should never really be calling setPath on a path it receives from the client, but there's no real ability to prevent them from doing it. Either way, it should be assuemd the framework itself is allowed to do whatever it wants. 
4) An extender to rsp-server. An extender to rsp-server such as wildfly could technically call setPath on a path received from the client before storing it in its own models. There is no valid reason to do this. However, even if we tried to restrict this usecase by not making setPath public, the extender could instead simply instantiate a new object with identical fields and a different path. Therefore, restricting access to setPath would achieve no benefit. 

We do store some daos in the models, specifically in the ServerPublishStateModel. The best way to protect against people changing the variables stored in the model are to only return clones of those objects wherever possible. While getDeployableState(reference) currently does return a clone,  getDeployableStates() returns a list with the same objects. It might be better to clone not just the list but each item, here. 

In general, java beans need to be protected from malicious usage. Usually this is accomplished by not storing them in the models, but this then requires costly conversion back and forth, from the dao to a storable class, and then back. The second best thing is to not return any object that is directly stored in a model by cloning everything when getters are accessed. 

Either way, we cannot remove setPath from the dao, as it is a java bean / dao, and is required. 
The only entities capable of changing it once it is stored in this map are either rsp-server itself, or the custom server adapter extension. In both cases, I would argue that both are allowed to do so, but probably have no valid use case to do so and thus should not do it. But this still doesn't mean we can remove or block the API.

**Comment by adietish** [comment]
@robstryker consistent cloning helps for sure but wont solve all situations:

once the user programmer changes the path in a reference the instance that's stored in the model will get orphaned. The model would not find it.

**Comment by robstryker** [comment]
I really don't understand your comment. If the model clones references when being added, and returns (again cloned) versions when they exit, then nobody has any opportunity to orphan an element in the model. The model receives the exact correct data when adding an item, and returns a new object 100% disconnected from the model when people ask to get whats in the model. 

Any client programmer who tries to call setPath() will only be talking to a dummy throwaway representation of the model and will have no ability to affect the model at all. 

Patch and test case here:  https://github.com/redhat-developer/rsp-server/pull/334/files

**Comment by robstryker** [comment]
Pushed the test. I'd say this issue is closed.   https://github.com/redhat-developer/rsp-server/pull/334
