### ISSUE TITLE
replace deprecated 'sonar.jacoco.reportPaths' by 'sonar.coverage.jacoco.xmlReportPaths'

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#321]
Sonar currently reports the current warning in our config:

```Property 'sonar.jacoco.reportPaths' is deprecated (JaCoCo binary format). 'sonar.coverage.jacoco.xmlReportPaths' should be used instead (JaCoCo XML format)```

**Comment by adietish** [comment]
@jkopriva want to address this?

**Comment by jkopriva** [comment]
@adietish yes, I will look at it.

**Comment by adietish** [comment]
@jkopriva great, thx!
