### ISSUE TITLE
When downloading a server, I should not have to provide my RH credentials several times

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#327]
steps:
1. EXEC: Download JBoss EAP 6.3
1. ASSERT: You're prompted to provide your RH credentials
1. EXEC: provide RH credentials
1. ASSERT: JBoss EAP 6.3 is downloaded and created in the "Servers" view
1. EXEC: Download JBoss EAP 7.1

Result:
You're prompted to provide your RH credentials again. 

Expected result:
Vscode should reuse the credentials that I already provided

**Comment by robstryker** [comment]
I'm really not sure hte UI should do this, unless it knows for absolute certain that the two server types are using the same credentials. This would require the notion of a credential domain, and having the core server expose which credential domains each server type uses.   

Remember, as currently coded, the vscode-adapters is meant to be 100% agnostic to server types. IF we eventually want to have custom logic for specific server types, we really need to break the vscode-adapters up into a mainUI and a set of extensions that can contribute to the mainUI in some fashion. 

Hard-coding EAP-specific stuff  (including storing the credentials)  into vscode-adapters should 100% be avoided.

**Comment by robstryker** [comment]
@adietish  can you move this isue to vscode instead?

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/commit/5cf6fba7cc09d5b5324e3fd2c3bc0ab020c7bb8f
