### ISSUE TITLE
Prevent multiple server creation from same runtime

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/rsp-server#331]
Let's suppose I want to create two wildfly15 servers. Now I have two options. Or creating them by downloading runtimes through vscode-adapters (ex. it will create wildfly-15.0.0.Final and wildfly-15.0.0.Final_1 under .org.jboss.tools.rsp.data/runtimes/installations) or associate runtimes to the servers manually. 

Currently there is no limitations at the number of servers I can associate to a single runtime and it can create some unexpected behavior to vscode-adapter side (ex. having the impression two server have different deployments). Can we check it before creating a new server?

**Comment by lstocchi** [comment]
Closing it. We could create multiple servers with the same runtime using different configurations

**Comment by adietish** [comment]
the reasoning behind closing this is the rule of thumb: if you can't do perfect magic, go for full power paired with great responsibility. If we'd be thriving for validating servers/deployments upon creation we'd have to make sure we'd have plenty of configuration options to check for and then making sure all those combinations would make sense. A goal that's pretty hard to achieve and we'd have to repeat it for every runtime that we support. On the other hand there are valid poweruser scenarios where a user wants to create different adapters with differing configurations (ex. one with java8, another with java11) for the same runtime. Given that we decided not to go this route, allowing users to create whatever adapters/deployments make sense to them not enforcing validity rules but leaving them to the user.
