### ISSUE TITLE
integration tests: should run all wildfly servers

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#346]
we should have the integration tests run all servers that we know. This then also implies that we dont run the integration tests in the PR checks but in a separate, continuous jenkins job.

**Comment by robstryker** [comment]
Rejecting this. I don't think we need this level of granularity, and we certainly don't need the 3 hour builds that come along with that.

**Comment by odockal** [comment]
In any case, we are going to support only two latest releases.
