### ISSUE TITLE
Error messaging unclear when adding deployment folder w no suffix

### ISSUE THREAD

**Issue by robstryker** [redhat-developer/rsp-server#361]
When a user attempts to add a deployment to wildfly that is a folder named "kitchensink", and does not override the optional deployment attribute "deployment.output.name",  the user is only told he cannot add this deployment. The reason for the rejection is unclear.

**Comment by adietish** [comment]
this is related to https://github.com/redhat-developer/vscode-adapters/issues/330

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/362

**Comment by adietish** [comment]
PR #362 lead to printing a java object reference in the error message: 
![image](https://user-images.githubusercontent.com/25126/58099000-085ede00-7bdb-11e9-952a-2eca6ca0b492.png)
Reopening.

**Comment by adietish** [comment]
filed a PR to correct this: https://github.com/redhat-developer/rsp-server/pull/368
