### ISSUE TITLE
Sending publishing/deployment requests with invalid/null values breaks the server

### ISSUE THREAD

**Issue by odockal** [redhat-developer/rsp-server#376]
During refactoring deployment/publishing integration tests I have encounter multiple server breakages while testing sending request to the server with invalid or null values. 

The list of method prototypes in RSPServer api definition that are breaking the server when null value is passed in as parameter:
- `public CompletableFuture<Status> publish(PublishServerRequest request);`
- `public CompletableFuture<Status> removeDeployable(ServerDeployableReference req);`
- `public CompletableFuture<Status> addDeployable(ServerDeployableReference req);`
- `CompletableFuture<Attributes> listDeploymentOptions(ServerHandle server);`
- `CompletableFuture<List<DeployableState>> getDeployables(ServerHandle handle);`

List of method prototypes that are breaking the server as well just while passing an invalid parameters:
- `public CompletableFuture<Status> publish(PublishServerRequest request);` when ie. `new PublishServerRequest(handle, 5000)` is passed in with invalid publish kind value, it is not breaking the server but it passes with status OK, which is wrong in my opinion.
- `public CompletableFuture<Status> addDeployable(ServerDeployableReference req);` when `new ServerDeployableReference(handle, new DeployableReference(WAR_FILENAME, null))` is passed in
- `CompletableFuture<Attributes> listDeploymentOptions(ServerHandle server);` when `new ServerHandle("foo.server.id", new ServerType("some.id", "my.server", "Random server type definition"))` is passed in
- `CompletableFuture<List<DeployableState>> getDeployables(ServerHandle handle);` when `new ServerHandle("foo.server.id", new ServerType("some.id", "my.server", "Random server type definition"))` is passed in

**Comment by odockal** [comment]
These test were introduced in https://github.com/redhat-developer/rsp-server/pull/375. So far, they are annotated with ignore, but one can use them for testing the fixes. Although, I would also update them to check proper calls from the server, so far, they check the status of the request and verifies that error is present which does not have to the proper check. It might return null, or other values...

**Comment by robstryker** [comment]
Just found this issue burried in my inbox. I will look into ti ASAP.

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/395

**Comment by robstryker** [comment]
Two of the APIs have no apparent way to send back errors. This will need an additional enhancement

**Comment by odockal** [comment]
@robstryker  Perfect, thanks, I am going to test it. Is there still something that needs to be adjusted? Any other changes in API to resolve this? If yes, the issue - so I can watch it.

**Comment by adietish** [comment]
@odockal #395 was merged. Dare to tests and confirm/refute that your issue was resolved, please?

**Comment by odockal** [comment]
@adietish @robstryker I have created a PR with not skipped failing tests except: https://github.com/redhat-developer/rsp-server/compare/master...odockal:followup-395?expand=1#diff-2d42e68474923bf11e0473c6a99201ebR154. There is still issue with server freeze. 

Others are test cases that fails due to the fact that I would expect something else in api call when passing null as parameter (ie. getting null instead of empty array) - https://github.com/redhat-developer/rsp-server/compare/master...odockal:followup-395?expand=1#diff-2d42e68474923bf11e0473c6a99201ebR204. But we can definitely discuss what should be returned when passing null/invalid value and not expecting status but rather array or object.

**Comment by robstryker** [comment]
> https://github.com/redhat-developer/rsp-server/compare/master...odockal:followup-395?expand=1#diff-2d42e68474923bf11e0473c6a99201ebR154. There is still issue with server freeze.

I'm not able to replicate a server freeze here, but I have replicated some bad output ;)

Status ERROR: org.jboss.tools.rsp.server.wildfly code=0 Server org.jboss.tools.rsp.server.model.internal.Server@25437828 does not support deployment with null path. null

I can fix that:
* be18adc9 - (HEAD -> master, origin/master, origin/HEAD) [#376] Fix a small error message issue (9 seconds ago) <Rob Stryker>

**Comment by odockal** [comment]
I will retest to see if I did something wrong, ie. rebuilding the rsp server, etc.

**Comment by robstryker** [comment]
I'm closing this issue, as most has been solved. Any specific cases can either get their own bug or ping me to see if it's a quick fix
