### ISSUE TITLE
Make build runs on windows machines as well

### ISSUE THREAD

**Issue by odockal** [redhat-developer/rsp-server#377]

**Comment by adietish** [comment]
@odockal how far is this? can this be considered finished or is there further work needed?

**Comment by odockal** [comment]
@adietish I have opened PR. @jrichter1 got some comments in PR so I am going to address them first.

**Comment by adietish** [comment]
@odockal did we fix this and simply went forgotten or was this done and simply not marked as resolved?

**Comment by odockal** [comment]
@adietish I am on it now. There was an issue, we closed the PR, yet I kept it in my branch and now I solved the issue and will bring this back to life! :)
