### ISSUE TITLE
Unstable itest WildFlyPublishingTest.testGetDeployablesEmptyDeployment

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/rsp-server#379]
Intermittent failure in the test when a deployment is being removed, seems to be a race condition.

**Comment by robstryker** [comment]
It'd be nice to include things like stack trace, point of failure, which assert dies, etc... to help people narrow down the issue

**Comment by odockal** [comment]
@robstryker This issue is assigned to me, it is itests problem, I know what is the problem there is no need for details, if you do not mind.

**Comment by odockal** [comment]
Did not run into this issue for quite a time. Closing, we can always reopen.
