### ISSUE TITLE
server doesn't save deployment field modified

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/rsp-server#392]
follows up on #386

Testing from server connector extension i found out that deployment field modification are not actually saved from server.

For instance if I have this json
```
{
  "server.home.dir": "/home/luca/.org.jboss.tools.rsp.data/runtimes/installations/wildfly-1600finalruntime/wildfly-16.0.0.Final",
  "id-set": "true",
  "org.jboss.tools.rsp.server.typeId": "org.jboss.ide.eclipse.as.wildfly.160",
  "id": "wildfly-16.0.0.Final",
  "deployables": {
    "deployable": {
      "label": "/home/luca/Public/github.com/redhat-developer/kitchensink/target/jboss-as-kitchensink.war",
      "path": "/home/luca/Public/github.com/redhat-developer/kitchensink/target/jboss-as-kitchensink.war",
      "options": {}
    }
  }
}
```

and I change the deployment label like this

```
{
  "server.home.dir": "/home/luca/.org.jboss.tools.rsp.data/runtimes/installations/wildfly-1600finalruntime/wildfly-16.0.0.Final",
  "id-set": "true",
  "org.jboss.tools.rsp.server.typeId": "org.jboss.ide.eclipse.as.wildfly.160",
  "id": "wildfly-16.0.0.Final",
  "deployables": {
    "deployable": {
      "label": "jboss-as-kitchensink.war",
      "path": "/home/luca/Public/github.com/redhat-developer/kitchensink/target/jboss-as-kitchensink.war",
      "options": {}
    }
  }
}
```

I receive an Ok message from the server but it actually haven't saved anything because if I ask for the same info it sends me the old value.

**Comment by adietish** [comment]
I have a slightly different behaviour:

steps:
1. ASSERT: have a wildfly server
1. ASSERT: have a deployment added to it
1. EXEC: "Edit Server", editor pops up with json
1. EXEC: change the label for your deployment
```
"deployables": {
    "deployable": {
      "label": 
```
1. EXEC: save the editor

Result:
Error pops up
![image](https://user-images.githubusercontent.com/25126/59273813-56ef1d80-8c59-11e9-8ed3-3069450cae81.png)

In vscode log (host IDE) I see the following error:
```
Message=Received response 'server/updateServer - (12)' in 7ms. data=Result: {
    "validation": {
        "status": {
            "severity": 4,
            "plugin": "org.jboss.tools.rsp.server",
            "code": 0,
            "message": "Could not load server from provided string: {\n  \"server.home.dir\": \"/Users/adietish/Downloads/runtimes/wildfly-17.0.0.Final\",\n  \"id-set\": \"true\",\n  \"org.jboss.tools.rsp.server.typeId\": \"org.jboss.ide.eclipse.as.wildfly.170\",\n  \"id\": \"wfl17\",\n  \"deployables\": {\n    \"deployable\": {\n      \"label\": \"kitchensink\",\n      \"path\": \"/Users/adietish/git/quickstart/kitchensink/target/kitchensink\",\n      \"options\": {\n        \"option\": {\n          \"deployment.output.name\": \"kitchensink.war\"\n        }\n      }\n    }\n  }\n}",
            "trace": "org.jboss.tools.rsp.eclipse.core.runtime.CoreException: Could not load server from provided string: {\n  \"server.home.dir\": \"/Users/adietish/Downloads/runtimes/wildfly-17.0.0.Final\",\n  \"id-set\": \"true\",\n  \"org.jboss.tools.rsp.server.typeId\": \"org.jboss.ide.eclipse.as.wildfly.170\",\n  \"id\": \"wfl17\",\n  \"deployables\": {\n    \"deployable\": {\n      \"label\": \"kitchensink\",\n      \"path\": \"/Users/adietish/git/quickstart/kitchensink/target/kitchensink\",\n      \"options\": {\n        \"option\": {\n          \"deployment.output.name\": \"kitchensink.war\"\n        }\n      }\n    }\n  }\n}\n\tat org.jboss.tools.rsp.server.model.internal.DummyServer.loadFromJson(DummyServer.java:34)\n\tat org.jboss.tools.rsp.server.model.internal.DummyServer.createDummyServer(DummyServer.java:18)\n\tat org.jboss.tools.rsp.server.model.ServerModel.updateServer(ServerModel.java:638)\n\tat org.jboss.tools.rsp.server.ServerManagementServerImpl.updateServerSync(ServerManagementServerImpl.java:360)\n\tat org.jboss.tools.rsp.server.ServerManagementServerImpl.lambda$13(ServerManagementServerImpl.java:356)\n\tat org.jboss.tools.rsp.server.ServerManagementServerImpl.lambda$27(ServerManagementServerImpl.java:655)\n\tat java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)\n\tat java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)\n\tat java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)\n\tat java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)\n\tat java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)\n\tat java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)\nCaused by: java.lang.NullPointerException\n\tat org.jboss.tools.rsp.launching.memento.JSONMemento.getString(JSONMemento.java:112)\n\tat org.jboss.tools.rsp.server.model.internal.Server.loadState(Server.java:132)\n\tat org.jboss.tools.rsp.server.core.internal.Base.load(Base.java:346)\n\tat org.jboss.tools.rsp.server.model.internal.DummyServer.loadFromJson(DummyServer.java:32)\n\t... 11 more\n"
        }
    }
}
```

**Comment by robstryker** [comment]
Patch for main issue:  https://github.com/redhat-developer/rsp-server/pull/402

**Comment by robstryker** [comment]
@adietish  I have seen that error (or similar) before. It is typically a parse error when the json sent over-the-wire is invalid in some way.  

If done from the CLI, it seems my CLI still has some bugs / race condition when dealing with large blocks of text. If done from vscode (as it appears yours is) that's 100% of the time an error in parsing the string. I'm updating the error message to be more clear:


Status ERROR: org.jboss.tools.rsp.server code=0 Update failed: Parse error while reading updated server: com.google.gson.stream.MalformedJsonException: Unterminated object at line 9 column 8 path $.deployables.deployable.label org.jboss.tools.rsp.eclipse.core.runtime.CoreException: Update failed: Parse error while reading updated server: com.google.gson.stream.MalformedJsonException: Unterminated object at line 9 column 8 path $.deployables.deployable.label

**Comment by robstryker** [comment]
@adietish I am unable to discover any behavior (disappearing servers) as you have indicated. However, if the server file itself seems normal and uncorrupted, then I'm really at a loss. There's no index file as far as I know keeping track of an index of which server files to read. 

ServerModel.java for example makes clear it will attempt to load any file in the servers folder: 


	public void loadServers(File folder) {
		if (!folder.exists()) {
			return;
		}
		for (File serverFile: folder.listFiles()) {
			Server server = loadServer(serverFile);
			if( server != null )
				addServer(server, server.getDelegate());

		}
	}

**Comment by redking00** [comment]
Dissapearing servers is bug #406. Issue parsing deployment options memento.

**Comment by robstryker** [comment]
This is fixed.
