### ISSUE TITLE
removing a deployment from wildfly creates a WARNING in server log

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-server#400]
Steps:
1. ASSERT have a wildfly server (ex. wildfly 16)
1. EXEC: add a deployment to it (ex. wildfly quickstarts/kitchensink)
1. ASSERT: have Autopublisher deploying it after 5s (server states: **(Synchronized)** once its done). Wait for the server log to report that it was deployed
```16:48:59,598 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 2) WFLYSRV0010: Deployed "kitchensink.war" (runtime-name : "kitchensink.war")```
1. EXEC: remove the deployment and let Autopublisher remove it

Result:
The error log shows a warning where the server complains that the war was removed but the .deployed marked stayed in place:
```
16:49:04,611 WARN  [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) WFLYDS0007: The deployment scanner found that the content for exploded deployment kitchensink.war has been deleted, but auto-deploy/undeploy for exploded deployments is not enabled and the kitchensink.war.deployed marker file for this deployment has not been removed. As a result, the deployment is not being undeployed, but resources needed by the deployment may have been deleted and application errors may occur. Deleting the kitchensink.war.deployed marker file to trigger undeploy is recommended.
```

**Comment by robstryker** [comment]
I'm not able to replicate this.   See WildFlyPublishController lines 79-86:


	@Override
	protected int removeExplodedModule(DeployableReference reference, 
			int publishType, int modulePublishType,
			File destination) throws CoreException {
		cleanAllMarkers(destination.getAbsolutePath());
		return super.removeExplodedModule(reference, publishType, modulePublishType, destination);
	}
	
We remove all marker files before removing the content. This works as expected for me. Can you try to trace through or ask someone else to test it as well?

**Comment by robstryker** [comment]
My output is as follows:

ServerOutput: org.jboss.tools.rsp.api.dao.ServerType@24cf1541:wf17a [org.jboss.ide.eclipse.as.wildfly.170:wf17a:1560359898101:p0][2] 13:18:42,495 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 78) WFLYUT0022: Unregistered web context: '/sample' from server 'default-server'

ServerOutput: org.jboss.tools.rsp.api.dao.ServerType@24cf1541:wf17a [org.jboss.ide.eclipse.as.wildfly.170:wf17a:1560359898101:p0][2] 13:18:42,540 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0028: Stopped deployment sample.war (runtime-name: sample.war) in 48ms

ServerOutput: org.jboss.tools.rsp.api.dao.ServerType@24cf1541:wf17a [org.jboss.ide.eclipse.as.wildfly.170:wf17a:1560359898101:p0][2] 13:18:42,590 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 2) WFLYSRV0009: Undeployed "sample.war" (runtime-name: "sample.war")

**Comment by robstryker** [comment]
@odockal  can you replicate?

**Comment by adietish** [comment]
same here, can't replicate this any more (using vscode-server-connector 0.20.2). Resolving.
