### ISSUE TITLE
Wildfly: Publishing new war wont work, not picked up and deployed (need to manually add .dodeploy marker)

### ISSUE THREAD

**Issue by lampsbr** [redhat-developer/rsp-server#458]
Hi, I'm currently unable to do the following:

- I have a "XYZ" webapp running in my wildfly instance.
- It's wildfly 12.0.0, beaultifully downloaded by RSP-ui.
- I open vscode on a different version of my "XYZ" webapp, make a new package of it with maven.
- Red Hat RSP Server starts, I start the wildfly instance, remove the deployment of the old version of my "XYZ" webapp,
- It syncronizes and the old version of the webapp "gets out".
- I add a new deployment, pointing to my new .war file. It's the same file name, but a different .war (different version of my webapp).
- I click Publish Server (full) again, but nothing happens. 

I can see in `C:\Users\myuser\.org.jboss.tools.rsp.data\runtimes\installations\wildfly-1200finalruntime\wildfly-12.0.0.Final\standalone\deployments` that there's a .war file there and a .undeployed file. Hitting publish server (full) and (incremental) doesn't change it. If I manually rename the file to .dodeploy, wildfly does it's job and it's succesfully deployed.

But shouldn't this deployment proccess work automagically? 

What data can I provide in order to help solve this issue (if it's an issue) ?

Thanks in advance. =)

**Comment by adietish** [comment]
@lampsbr can you reproduce this in wildfly 12 only or is it happening in other versions of wildlfy too?

**Comment by lampsbr** [comment]
I tried the same steps using wildfly 9.0.2 (fresh install, provided by the ui in vscode).

Same behavior happens. I can see in deployments directory that the new .war file is there, there's a .undeployed status file, but the publish buttons don't change anything.

**Comment by adietish** [comment]
this is related to #400

**Comment by adietish** [comment]
Using the latest vscode-server-connector 0.20.2 I can't replicate this. I see the deployment markers being created by the adapter. Resolving. 
@lampsbr please feel free to reopen this if you can't confirm my findings.

**Comment by robstryker** [comment]
Thanks for verifying, @adietish .  @lampsbr  are you using 0.20.2? Or some earlier version? Let us know if using 0.20.2 fixes the issue.

**Comment by lampsbr** [comment]
I'm using server connector v0.20.2.
Is there some sort of log I can attach here to help find out what happens? The only artifacts I deploy are a sql driver and my webapp. Maybe there's something wrong in my webapp. ¯\_(ツ)_/¯
