### ISSUE TITLE
Update com.fasterxml.jackson.core:jackson-databind to 2.9.10 or later

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rsp-server#469]
GitHub security has reported an issue with jackson-databind.

See https://github.com/redhat-developer/rsp-server/network/alert/api/docs/org.jboss.tools.rsp.schema/pom.xml/com.fasterxml.jackson.core:jackson-databind/open

**Comment by adietish** [comment]
@jeffmaury your link leads to 404. Looking into the security tab of rsp-server, I can't spot this either?

**Comment by jeffmaury** [comment]
You did not get access to security alerts. Should be ok now

**Comment by robstryker** [comment]
This is not an issue worth fixing. Jackson is not used in the runtime at all.  It is solely used to generate docs.
