### ISSUE TITLE
Alternate JDK to 1.7

### ISSUE THREAD

**Issue by alansferreira** [redhat-developer/rsp-server#494]
Hi there!! 
I'm work in an project that's use Jboss AS 7.1, and requires an specific version of JDK, 1.7 to run.

I can change server config to run with another JVM like 1.7?

Thank's!

**Comment by robstryker** [comment]
You should be able to do this, yes. When you create a new server, it should ask if you want to complete the optional attributes. One of the optional attributes should be to choose a java VM to use. Let me know if this works or doesn't work for you.

**Comment by robstryker** [comment]
@alansferreira  Did you figure out how to use this feature? Or do you need a bit more help?

**Comment by robstryker** [comment]
You can see overriding the jdk / jre here:  https://youtu.be/sP2Hlw-C_7I?t=327

This is the create-new-server workflow. Time 6m35s goes into the idea of optional attributes, and 7m25s starts talking about overriding your jdk for wildfly.
