### ISSUE TITLE
Prevent Jenkins job to run when no modifications are pushed

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rsp-server#511]

**Comment by robstryker** [comment]
I believe this was fixed by * 4b773228 - Update Git repo URL in Jenkinsfile (2 days ago) <Jeff MAURY>

**Comment by odockal** [comment]
@robstryker  How does the change in the commit solves this issue? @jeffmaury What job do you have in mind? Pr check I guess...

**Comment by jeffmaury** [comment]
No the changes was related to master build
