### ISSUE TITLE
Tycho build breaks codecov reports

### ISSUE THREAD

**Issue by psrna** [redhat-developer/rsp-server#52]
Seems that with the change to tycho build, project structure has changed resulting in jacoco not collecting coverage reports.

**Comment by robstryker** [comment]
Merged

**Comment by psrna** [comment]
@jeffmaury @robstryker @jrichter1, guys I still see empty coverage on codecov.io (see: https://codecov.io/gh/redhat-developer/rsp-server) even though new builds are passing.
