### ISSUE TITLE
Set up custom deployment folder

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/rsp-server#531]
There are a couple of issues opened related to this (https://github.com/redhat-developer/vscode-server-connector/issues/423, https://github.com/redhat-developer/vscode-rsp-ui/issues/103) . Currently we don't have an option to set up a custom deployment folder and everything is stored inside standalone/deployment. 

@robstryker should we add a new parameter in the edit server so users can specify a custom deployment folder?

**Comment by robstryker** [comment]
I'll look into this.
