### ISSUE TITLE
Not loading existing servers on startup with WSL

### ISSUE THREAD

**Issue by epomatti** [redhat-developer/rsp-server#594]
### Environment
- Operating System: WSL2 with Ubuntu 20.04
- JDK version: openjdk 11.0.8 2020-07-14
- Visual Studio Code version: 1.48.0
- Java extension version: openjdk 11.0.8 2020-07-14

I installed a WildFly server and it is running OK. However, when I close VS Code and open it again the server is gone:

![image](https://user-images.githubusercontent.com/6530769/90522207-d15edb80-e141-11ea-8bb1-45542d8a5d9e.png)

If I create another server then the previous server shows up along with the new one. This happens every time I close and open VS Code:

![image](https://user-images.githubusercontent.com/6530769/90522242-da4fad00-e141-11ea-9465-23fe1385a53b.png)

Here is a video:

![maibeer-httpsonly](https://user-images.githubusercontent.com/6530769/90522312-efc4d700-e141-11ea-987a-b658ac46569f.gif)

**Comment by robstryker** [comment]
Closing as fixed under https://github.com/redhat-developer/vscode-rsp-ui/pull/133

Please re-open if it's not fixed
