### ISSUE TITLE
Server has unknown status after start

### ISSUE THREAD

**Issue by jkopriva** [redhat-developer/rsp-server#615]
[kind/bug]

## What versions of software are you using?
- Operating System: MacOS 10.15
- IntelliJ version:
- Intellij-rsp extension version: built from master

## What did you run exactly?
Community Server -> Download new server -> Select Apache Tomcat 9.0.30 -> Started

## Actual behavior
Server has status: 
![image](https://user-images.githubusercontent.com/17871936/98339037-6370d480-200b-11eb-81df-70c770f7798c.png)

## Expected behavior
Server has status Started - I am not sure about the second status

**Comment by robstryker** [comment]
I've decided this isn't really an issue and certainly not a regression. The user can full-publish here if they wish.
