### ISSUE TITLE
Restarting (stop/start) of RSP provider leads to detecting wrong state of its server (ie. eap)

### ISSUE THREAD

**Issue by odockal** [redhat-developer/rsp-server#632]
1. Open VSCode and servers view
2. Assert: RSP gets started
3. Create server (eap or wildfly)
4. Assert: Server is created and its state is stopped
5. Stop RSP
6. Start RSP
7. Assert: RSP is stared
8. Assert: eap or wf server is detected as stopped
Actual result: Server is marked as started, it cannot be stopped (there is connectionRefused error) or terminated. Thus it cannot be even deleted via remove server

**Comment by odockal** [comment]
![rsp-restart-broken-server-state](https://user-images.githubusercontent.com/19164299/107783542-ac42d280-6d4a-11eb-8127-401eedb76e78.gif)

**Comment by odockal** [comment]
I have built extension locally (vscode-server-connector from master branch) with using latest stable RSP bits.

**Comment by odockal** [comment]
Previous released version of server-connector does not do that.

**Comment by robstryker** [comment]
User error. User had jenkins running on 8080.

**Comment by odockal** [comment]
Even though this issue is properly closed here I am thinking that having running app on 8008 should not prevent you from working with server and wrongfully identifying server state, right? So I am opening https://github.com/redhat-developer/vscode-rsp-ui/issues/159
