### ISSUE TITLE
Cannot Edit Server (wildfly, tomcat, etc.)

### ISSUE THREAD

**Issue by odockal** [redhat-developer/rsp-server#643]
1 .Having started RSP (even community) 
2. Have set any server (ie. wildfly)
3. Edit server
4. Assert: Server config appear in editor
Actual result: Nothing obvious happens, in developer tools console there is this error:
```
  ERR The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
	at Function.from (buffer.js:331:9)
	at Function.fromString (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:56:26590)
	at Function._serializeReplyOKJSON (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:15754)
	at Function.serializeReplyOK (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:15423)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:8877
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by odockal** [comment]
oh, after like 10 minutes I got this error message:
```
Error running command server.editServer: Canceled. This is likely caused by the extension that contributes server.editServer.
```

And this error stack trace appeared in developer console:
```
ERR Connection got disposed.: Error: Connection got disposed.
	at Object.dispose (/home/odockal/.vscode/extensions/redhat.java-0.76.0/dist/extension.js:1:80768)
	at Object.dispose (/home/odockal/.vscode/extensions/redhat.java-0.76.0/dist/extension.js:1:140455)
	at /home/odockal/.vscode/extensions/redhat.java-0.76.0/dist/extension.js:1:137111
```

**Comment by robstryker** [comment]
I'm not able to replicate this at all. 
Versions of everything?

**Comment by odockal** [comment]
thanks for confirmation. I tried various versions of rsp-ui, server connector and vscode studio (even insiders). Jan also reproduced. I cannot reproduce now as vscode version came out in a meantime and the issue seems to be gone. I will try again after testing...

**Comment by odockal** [comment]
It is NOT reproducible in this matrix (it happened in both connectors - standard and community):
VScode 1.54.3
RSP-Server-community: 0.23.10
Server-Connector: 0.23.10
RSP-UI: 0.23.8

**Comment by odockal** [comment]
Oh, this is https://github.com/redhat-developer/vscode-rsp-ui/issues/163 issue. Already fixed in master. We should release rsp-ui...

**Comment by odockal** [comment]
It is reproducible with 0.23.7.

**Comment by robstryker** [comment]
So the "Connection got disposed." error is from redhat-java, which we don't use at all when editing a server. We just open a json editor. I can't see any way this is related to our extensions. 
For the otehr two traces, well, they don't reveal a damn thing honestly. None of our code appears to be in the stack, and, to my knowledge, I didn't change any function signatures any time recently at all, especially not in the edit-server call heirarchy.

**Comment by odockal** [comment]
Rob, we are hunting ghosts, this was already fixed as I said in master branch for rsp-ui:
> Oh, this is redhat-developer/vscode-rsp-ui#163 issue. Already fixed in master. We should release rsp-ui...
