### ISSUE TITLE
Switch capabilities protocol to request

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rsp-server#67]
The current implementation of the capabilities protocol is server to client oriented and it cause troubles and has some drawbacks.
First, the server send a get capabilities request immediately after connection but seems the response is never returned by pre 0.10 clients and the server is waiting indefinitely for the response.  Also the vscode-adapters is using a JS lib to check that the server is correctly started that will try to check that the TCP port is established and for whatever reason, this check is now rejected because it's too long.

So my proposition is the following:
- consider by default any client being 0.0.9
- upon connection, the client will send a capability request with all capabilities it supports. We could also add in the response the accepted capabilities the server has accepted so that a greater client (which is unlikely to happen but we never know) can talk to a lesser server and knows what the server supports

Regarding the prompt string, I found another drawback: if the user give a bad password, then the storage cannot be opened but there is no way for the client to know it. We have two solutions for that:
- change to a request from the client. The server will send a notification (please authenticate) and the client will send a request. As it is a request from the client to the server, then there will be a response and the client will know if it has been accepted or not. But I understand that this will complexify the start server workflow
- add a new notification claiming is authentication has been accepted or not but user/client will be unable to correct

WDYT ?

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/68

This PR only addresses the first half (capability request).  Requesting credentials is still done nearly on startup (when a client registers capabilities, we will fire a new thread to request secure storage).

**Comment by robstryker** [comment]
First half resolved. Please see issue 70 for 2nd half
