### ISSUE TITLE
Add support for cluster flags in CDK/Minishift server

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rsp-server#69]
As odo is using the service catalog, we should be able to specify cluster specific flags (service catalog, metrics,....) to get those features enables in the cluster

**Comment by robstryker** [comment]
Can you please elaborate more on this? Link to flags, etc etc?

**Comment by jeffmaury** [comment]
service-catalog, template-service-broker

**Comment by robstryker** [comment]
Yeah this doesn't actually elaborate anything.  I've googled "cdk service-catalog"  and "cdk template-service-broker"  and can't seem to find out what the flags or args are.

**Comment by robstryker** [comment]
Fixed in 2bb738d2074001ea46d2b6c7a41173e5903273cd
