### ISSUE TITLE
Preferences should be stored in user workspace instead of $HOME folder

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rsp-server#72]
We should stored preferences in user workspace folder. That would allow user to manually edit the files so that extra flags don't need UI to be managed. That would probably required a change in the protocol as rsp-server needs to know that folder. We could add it to the capabilities request

**Comment by robstryker** [comment]
Please use -Dorg.jboss.tools.rsp.data=/some/path  when launching RSP. 

Closed, bug is 'not_rsp'
