### ISSUE TITLE
Request for EAP 8.0.z.GA support

### ISSUE THREAD

**Issue by nagetsum** [redhat-developer/rsp-server#725]
Environment:
- Visual Studio Code 1.88.1
- Server Connector v0.26.15

Issue:
Unable to add JBoss EAP 8.0.0.GA to Red Hat Server Connector.

Steps to reproduce:
1. extract jboss-eap-8.0.0.zip to ~/
1. select Create New Server... 
![1_steps-to-reproduce](https://github.com/redhat-developer/rsp-server/assets/2845828/e9830ab6-18f4-40a1-9aa8-0f8b7a0554a8)
2. Choose "No, use server on disk"
![2_steps-to-reproduce](https://github.com/redhat-developer/rsp-server/assets/2845828/484ceb96-6a6e-4429-a7eb-569326c592df)
3. Select ~/jboss-eap-8.0
4. We can see "could not detect any server at /home/nagetsum/jboss-eap-8.0!
![3_steps-to-reproduce](https://github.com/redhat-developer/rsp-server/assets/2845828/33599a85-f930-48fb-8e60-f414fc6c8804)

Just my observation:
- It works with jboss-eap-8.0.0.Beta.zip
- It looks that  rsp-server loads `JBOSS_HOME/modules/system/layers/base/org/jboss/as/product/eap/dir/META-INF/MANIFEST.MF` to determine the specified server version in [ServerBeanTypeWildflyPlus.java](https://github.com/redhat-developer/rsp-server/blob/v0_26_9/runtimes/bundles/org.jboss.tools.rsp.server.wildfly/src/main/java/org/jboss/tools/rsp/server/wildfly/beans/impl/ServerBeanTypeWildflyPlus.java#L78-L81)
- Due to [WFLY-18578](https://issues.redhat.com/browse/WFLY-18578) and [JBEAP-26314](https://issues.redhat.com/browse/JBEAP-26314), module layout of org.jboss.as.product module has been changed then MANIFEST.MF has not put in the module dir. Just my guessing,  installation directory of 8.0.0.GA is not identified due to WFLY-18578 and JBEAP-26314.
```
$ tree jboss-eap-8.0/modules/system/layers/base/org/jboss/as/product
jboss-eap-8.0/modules/system/layers/base/org/jboss/as/product
└── main
    ├── module.xml
    └── wildfly-ee-feature-pack-product-conf-8.0.0.GA-redhat-00011.jar

1 directory, 2 files
```

Sorry, I'm new to vscode plugin code and not sure how to fix it. It would be very helpful to be able to work with JBoss EAP 8.0.z.GA. We have related a plan for EAP documentation in [EAP7-2187](https://issues.redhat.com/browse/EAP7-2187).

**Comment by robstryker** [comment]
I'll look into this. Thanks.
