### ISSUE TITLE
Add support for MINISHIFT_HOME for CDK/minishift

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rsp-server#76]
The MINISHIFT_HOME parameter is not exposed by CDK/Minishift server types. Could be added as an optional parameter

**Comment by robstryker** [comment]
PR https://github.com/redhat-developer/rsp-server/pull/89/files   uses environment-variable instead, which is supported.

**Comment by jeffmaury** [comment]
Bad PR link, should be #85

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/85
