### ISSUE TITLE
CLI does not support all server request types

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rsp-server#78]
CLI does not support:
- getServerTypes
- getRequiredAttributes
- getOptionalAttributes

**Comment by robstryker** [comment]
when doing an 'add server', it does a getServerTypes() and does a getRequiredAttributes and a getOptionalAttributes 

Are you suggesting each of these calls should be exposed to the user via the CLI? I'm not sure it's exactly necessary but I guess I can make it happen...

**Comment by robstryker** [comment]
Done
