### ISSUE TITLE
Preferences should be stored as JSON instead of XML

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rsp-server#83]
In order for us to allow user editing the various preferences files, we should use JSON instead of XML as this is the standard on VSCode.
The impacted files are:
- server files
- vms

Discovery paths are stored as a list of string so we might migrated it as well

**Comment by robstryker** [comment]
@bdshadow  Did you commit this without a PR / review?

**Comment by bdshadow** [comment]
@robstryker why do you think so? there is a PR here: https://github.com/redhat-developer/rsp-server/pull/105. It's not reviewed and not merged

**Comment by robstryker** [comment]
This was merged
