### ISSUE TITLE
Use GIT based version qualifier

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rsp-server#92]
As JBoss Tools, we should use GIT based version qualifiers as it reflects better the changes done on a bundle

**Comment by dgolovin** [comment]
@jeffmaury do you suggest using git hash as a qualifier?

**Comment by jeffmaury** [comment]
Not exactly but rather use the date of the last commit in the tree: that allows us to get different qualifiers for the different bundles that will reflect when the last modification has been done: ex when api is stable the qualifier will reflect an old date and likely runtimes bundles will get newer dates. Also the git hash is stored in the manifest. See https://github.com/jbosstools/jbosstools-build/blob/master/parent/pom.xml#L196

**Comment by robstryker** [comment]
Old, not gonna do it
